# Generated by Django 2.2.3 on 2019-09-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critic', 'my_manual_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='author_name',
        ),
    ]
