# Generated by Django 2.2.3 on 2019-08-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0006_auto_20190820_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=0)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('screen_writer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='critic.Movie'),
        ),
    ]
