# Generated by Django 2.2.3 on 2019-08-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0008_auto_20190820_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critic.Movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critic.Movie'), max_length=100),
        ),
    ]
