# Generated by Django 2.2.3 on 2019-08-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0011_auto_20190821_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='movie',
        ),
    ]
