# Generated by Django 2.2.3 on 2019-08-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0012_auto_20190821_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
