# Generated by Django 2.2.3 on 2019-09-25 06:30

from django.db import migrations

def set_review_authors(apps, schema_editor):
    # from critic.models import Review, Author
    Review = apps.get_model('critic', 'Review')
    Author = apps.get_model('critic', 'Author')

    for review in Review:
        author.name, created = Author.objects.get_or_create(name=review.author_name)[0]
        author.save()


def undo_setting_review_authors(apps, schema_editor):
    Review = apps.get_model('critic', 'Review')
    Author = apps.get_model('critic', 'Author')
    # ...


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0016_auto_20190926_0133'),
    ]

    operations = [
        migrations.RunPython(set_review_authors, undo_setting_review_authors),
    ]
