# Generated by Django 2.2.3 on 2019-09-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0017_manual_migration_for_authors'),
    ]

    operations = [
    ]
