# Generated by Django 2.2.3 on 2019-11-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0018_auto_20191108_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='movies/cover/'),
        ),
    ]
