# Generated by Django 2.2.3 on 2019-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0019_auto_20191114_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_rating',
            field=models.IntegerField(null=True),
        ),
    ]
