# Generated by Django 2.2.3 on 2019-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0020_review_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate5',
            field=models.IntegerField(default=0),
        ),
    ]
