# Generated by Django 2.2.3 on 2019-11-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0021_auto_20191116_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
