# Generated by Django 2.2.3 on 2019-11-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0022_movie_rank'),
    ]

    operations = [
    ]
