# Generated by Django 2.2.3 on 2019-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critic', '0022_movie_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(blank=True, default='movies/cover/default-cover.png', null=True, upload_to='movies/cover/'),
        ),
    ]
